export const CALBAYOG_BARANGAYS = [
  "Aguit-itan",
  "Alang-alang",
  "Alicante",
  "Amampacang",
  "Anislag",
  "Ba-ac",
  "Babalatan",
  "Badang",
  "Bagacay",
  "Bagbrag",
  "Bagon de Taas",
  "Bahi",
  "Baluarte",
  "Balud",
  "Banjao",
  "Bawod",
  "Bayangan",
  "Begaho",
  "Bicobian",
  "Bino-ongan",
  "Bito",
  "Buga",
  "Bugtong",
  "Bungtow",
  "Cabacungan",
  "Cabagatan",
  "Cabugawan",
  "Cag-anibong",
  "Cag-olango",
  "Cagbanao",
  "Cagbibi",
  "Cagmanipis Norte",
  "Cagmanipis Sur",
  "Cagnipa",
  "Calao",
  "Caloloma",
  "Cambaque",
  "Cambaro",
  "Can-abay",
  "Can-adan",
  "Can-imang",
  "Can-ois",
  "Cang-malat",
  "Capoocan",
  "Carayman",
  "Caster",
  "Catabunan",
  "Cawayan",
  "Cinco",
  "Cogon",
  "Dagum",
  "Dawo",
  "De Maria",
  "Dinagan",
  "Dinawacan",
  "Esperanza",
  "Gabay",
  "Gadgarad",
  "Gasague",
  "Gerengang",
  "Granada",
  "Guimbaoyan Norte",
  "Guimbaoyan Sur",
  "Hamorawon",
  "Helino",
  "Higante",
  "Iba",
  "Ibatan",
  "Jacinto",
  "Jose A. Roño",
  "Kagasacan",
  "La Paz",
  "Langoyon",
  "Lanta",
  "Lantao",
  "Ligaya",
  "Limaway",
  "Looc",
  "Luluway",
  "Macatingog",
  "Mag-ubay",
  "Magsaysay",
  "Mahayag",
  "Malajog",
  "Malalag",
  "Malcasabol",
  "Maloco",
  "Manaing",
  "Manarapan",
  "Mancol",
  "Manguino-o",
  "Manuel Barral Sr.",
  "Marangtang",
  "Matobato",
  "Mawacat",
  "Maybo",
  "Migara",
  "Naparasan",
  "Nawawao",
  "Nijaga",
  "Obrero",
  "Oquendo District",
  "Orense",
  "Panangan",
  "Panas",
  "Panlayahan",
  "Pawa",
  "Pilar",
  "Pinamorotan",
  "Polangi",
  "Rawis",
  "Rizal",
  "Roxas",
  "Salabag",
  "Saljag",
  "San Antonio",
  "San Isidro",
  "San Jose",
  "San Policarpo",
  "San Vicente",
  "Santa Margarita",
  "Santo Niño",
  "Sapat",
  "Sinidman Norte",
  "Sinidman Sur",
  "Tabawan",
  "Tagab-iran",
  "Tarabucan",
  "Tiguma",
  "Tinambacan Norte",
  "Tinambacan Sur",
  "Tinaplacan",
  "Tomuglob",
  "Trinidad",
  "Villarosa",
  "Wright"
].sort();

export default CALBAYOG_BARANGAYS;
